### ISSUE TITLE
Add tests for KV store.

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#109]
Cover basic functionality of this feature in the tests here:
https://github.com/nimbella/nimbella-cli/tree/master/tests

**Comment by saxena52** [comment]
I created tests for the following commands: kv get/set, clean, list, del, expire, and ttl. I will later add tests for getMany, llen, lrange, rpush, and setMany since I noticed they did not seem to work. Also, I noticed there are not any tests for "web" and "object", should we add tests for these commands as well?

**Comment by jthomas** [comment]
Thanks for this - it's a great addition. Definitely feel free to move onto those other features.
