### ISSUE TITLE
improve error message when a web bucket is not available

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#19]
An observation based on a user's experience, the error message printed when an account does not have web storage (but it is needed to deploy) is confusing. Here is the current message:

```
> nim project deploy /some/path/to/project/with/web/folder
 ›   Error: Deployment of web content to namespace 'some-namespaces' requires a storage key but
 ›   none is present
```

Here storage means object storage. We should improve this error message and align it with the evolution of the nomenclature around "file store".

**Comment by joshuaauerbachwatson** [comment]
I'd like to generalize this issue to everything shown to users and typed by users to refer to the different kinds of storage.  The use of "storage" to mean "buckets" is historical and increasingly unhelpful.

In the current documentation effort we are saying that a (typical) user has two "file stores" (data and web) and one "key-value" store.    The presenting message that Rodric posted should say (approximately) "requires web store authorization".   The headings in `auth list` should be something like `file-store` and `key-val` rather than "storage" and "redis".   Similarly, the flags and outputs on `auth current` (etc).   In the case of flags typed by the user we should accept the legacy values to avoid a breaking change.

**Comment by joshuaauerbachwatson** [comment]
In PR #67 @bhageena made some basic useful changes covering what was asked for but then asked if we should go further.  I think I asked that we track down everything that is shown to users concerning buckets and make the terminology regular.  So, I think that's the goal.   It might take some searching to track down all those places and we might miss some.  So I am neutral on whether we try to exhaustively do that in this PR or just call this a good step in the right direction.  Chandan, I think that's your call.   If you want to do more under this PR and it's in keeping with this direction, you can keep at it but I'm also fine if you want to upgrade to a reviewable PR and I'll review and merge it.

**Comment by bhageena** [comment]
I was thinking of renaming the variable and action names to exclude 'redis' but that's quite a change touching multiple repos. Also that doesn't seem to be required, for now, only user-facing nomenclature should be changed. We have been consistent in calling redis as 'Key-Value' store on the UI. So opening #67 for review, as it fulfills the immediate requirement.

**Comment by joshuaauerbachwatson** [comment]
I agree with your decision as it applies to code.   The scope here should be limited to the UI.  Developers working with this code base can understand and bridge the gap since it is certainly obvious in the code that we use redis to implement key-value.

**Comment by joshuaauerbachwatson** [comment]
Self-assigning as reminder that this is awaiting a stable version.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.13
