### ISSUE TITLE
improve action wrapping for arbitrary web builds

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#30]
The current (undocumented) feature for action wrapping web assets turns a web file into an action. Without using API gateway for arbitrary API to file mapping, the OW web action model doesn't permit arbitrary nesting (restrict to `/` and `/one-level` directories).

An alternative is to zip up the entire web folder and add a router to it instead.
So the zip file would contain:
```
- router.js
|_ web
   |_ index.html
   |_ static
       |_ style.css
```

Where `router.js` implements a router to map `__ow_path` received by the web action to a file path relative `web`.

The router in quasi pseudocode:
```
const fs = require('fs')

function main(args) {
   let path = args.__ow_path || 'index.html'
   const content = fs.readfileSyc(path)
   const type = getTypeForExtenstion(path.split('.')[-1] // get the last part of the file name
   return { 
      body: type.isBinary ? base64Encode(content) : content
      header: { 'content-type': getContentType(type) }
   }
}
```

This is being prototyped by @programmersstudio as user level. If it proves useful, we should consider using it as the basis for `nim`'s implementation of action wrapping in general.

A caveat to note to this approach is that the web build must use relative paths for the file inclusions.

**Comment by joshuaauerbachwatson** [comment]
It is not immediately clear to me how the pseudo-code posted by @rabbah translates to a clear design for adding the feature to the deployer.   I am inhibited by not having been party to the one-off implementation that was done by @programmersstudio.   I need to get briefed on how _that_ worked so I can think about how to generalize it.   It seems to me that this is not an easy problem given the constraints.   Something that runs during the "prepare" phase (as action wrapping does now) can't use the file system for staging, so we are talking about potentially zipping a large amount of material into memory.   Are we talking about one big honking action that analyzes all the paths and does all the routing?  Or something more subtle?

@rabbah if you can clarify what you had in mind that would be great.

@programmersstudio if you can lay out, here, what you did in the special case and your initial ideas / attempts for generalizing it, that would be great.

Meanwhile, I'm being asked to help with this (and I think I should, since there are many caveats to changing the deployer) but I don't understand the proposal.

**Comment by joshuaauerbachwatson** [comment]
Putting the previous comment into perspective:  I know I was involved in suggesting that this could or even should be a feature of the deployer, so, not blaming anyone.  But: (1) action wrapping is still currently undocumented.  (2) A major expansion in its scope would need to be tested and supported if it's going to be of any use.  (3) The immediate problem (commander code editor on Vz) is solved by what Pulkit has already done.  (4) We are meanwhile actively engaged in efforts that should make buckets available in systems that didn't used to have them, resulting in less demand for action wrapping in the long run.   In addition to being clear about how this could work, if we are indeed going to do it, we should also consider not doing it 🙂 .

**Comment by programmersstudio** [comment]
I tried 2 approaches.

1) Using FS
As we cannot use FS because using it will break the remote project deployment (Github for example) for Workbench

2) I was thinking what if we remove the nested directory check and deploy the project straight away. I first tried it with a non-nested project structure, where, I deployed 3 files `index.html` being the main file which was calling other 2 `js` and `CSS`. This was working fine.
Therefore, I thought if OW will deploy the nested files in the same way then this might work.

For example - `index.html` is calling external css file present in `/css` directory and the file name is `main.css`, hence the filePath will be `./css/main.css` and the `actionWrap` name is `project_1`. If could deploy the project like this then it might work.

- `${actionWrap}/project_1/index.html`
- `${actionWrap}/project_1/css/main.css`

OW was throwing the error `resource not found` while I was trying this method. However, while debugging I checked that file was read by the reader and `code` variable was not null.

**Comment by rabbah** [comment]
> OW was throwing the error resource not found while I was trying this method. However, while debugging I checked that file was read by the reader and code variable was not null.

I hinted at this in slack. To have a single router will require either using an API gateway, or mangling the URL generation to be relative (to `index.html` as in `index.html/css/main.css`). Not particularly elegant.

> we should also consider not doing it

OK - we can shelve this for now.

The action wrapping that exists but undocumented will only work for one level of nesting, and so should not be used liberally in the absence of buckets, and should remain undocumented.

**Comment by joshuaauerbachwatson** [comment]
Based on discussion here, and my assessment of the difficulties and actual benefits,  and with concurrence from @rabbah I am closing this issue.
