### ISSUE TITLE
Feature: accept github url as project location for deploy

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#33]
If you try to deploy a project from the github URL displayed in the browser, e.g., https://github.com/nimbella/demo-projects/tree/master/chat it is not accepted:

```
Error: The repository path 'nimbella/demo-projects/tree/master/chat' is not recognized by GitHub
```

It would be very convenient if we could support this because it permits copy/paste (url) deploys more conveniently.

The accepted syntax now requires a rewrite of the url to `github:nimbella/demo-projects/chat`.

**Comment by joshuaauerbachwatson** [comment]
Actually (not that this helps in itself) the minimal rewrite would be `https://github.com/nimbella/demo-projects/chat` because we do recognize that prefix and would already be parsing the organization and repo correctly.

What's needed is to recognize the initial path segment `/tree` as special and parse `/tree/${commit-ish}/${repo-path}`  equivalent to how we currently parse `${repo-path}#${commit-ish}`.    Although `master` is the default and could be omitted, it does not need to be omitted to have a valid result.

Unless we want to be even more clever, this would mean that you can't have a valid `repo-path` that starts with `tree`.

**Comment by joshuaauerbachwatson** [comment]
Done.   Awaiting stable version.

**Comment by joshuaauerbachwatson** [comment]
This work is done and the feature is listed in the (committed) change log for 1.14.   1.14 is not released yet but is slated to be released during a upcoming knowledge transfer session.   With the listing of the change in the log the need to hold this issue open is gone.
