### ISSUE TITLE
nim object url error

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#43]
```
> nim object url xxx
h
```

the file `xxx` does not exist.

**Comment by joshuaauerbachwatson** [comment]
I've committed a fix for this.

It actually doesn't matter whether the file exists or not.  When you generate a signed url there is no requirement that the file exist (for example you might be expecting the recipient of the signed url to upload the file contents).

The problem was that when I introduced storage abstraction, the abstract version of many functions in the storage client API differed somewhat from the Google functions they were based on in order to make it easier to get to a common base with s3.  Internally to nim, all uses of the old Google-specific handle were supposed to be converted to use the newer abstract one.   However, I missed this one call site which still thought it was calling the Google version of the function (the function name was the same, just the semantics of the handle providing the function changed a bit).   Awaiting a stable version.

**Comment by joshuaauerbachwatson** [comment]
Fix is in stable version 1.11
