### ISSUE TITLE
Feature: nim web:serve

### ISSUE THREAD

**Issue by sciabarracom** [nimbella/nimbella-cli#45]
When you develop the frontend to nimbella, a common occurence is runnin your front-end development kit locally, to iterate development, with live reload, while being able to execute functions in the cloud.

So far I managed with a complicated setup where I change the URL for api requests (`if location.href==localhost.. else...`.) and also I need to disable cors in the browser.  Overall annoying and not that simple.

A way simpler way is of course using a web server with proxy. I found this solution:

`http-server project/web --proxy https://$(nim auth current)-apigcp.nimbella.io`

Much better would be to have this function embedded.

`nim web:serve [web]` will start a web server that server the content of the folder web and the proxies the '/api' path to the current namespace endpoint, as I did in the command that I run manually (but here I have to install npm and http-server separately).

**Comment by joshuaauerbachwatson** [comment]
I like what I see in draft PR #66 as far as functionality.  I'll review it more carefully once we discuss something that I should have commented on immediately when this issue was opened.

There is a question in my mind whether this command should be positioned under `nim web` or perhaps better positioned under `nim project` (maybe `nim project serve-web`, to be someday complemented by `serve-actions` or `serve-openwhisk`).   The syntax of the command that @bhageena chose (which seems fine to me in itself) I think makes it belong more under project.   I think of `nim web` as being about web _entities_ (items in the web file store).  Note that as it stands (by design) it serves from the local web folder and not from the actual web file store.   I'd like some more opinions on this.   Of course, it should then be an easy rename operation if we want to move it.

**Comment by rabbah** [comment]
It makes senses under project. Because the value is for both web and apis ultimately.

**Comment by bhageena** [comment]
It's been moved as `nim project serve-web`, excited to explore other possibilities viz `serve-actions` or `serve-openwhisk`

**Comment by joshuaauerbachwatson** [comment]
Added self-assignment as reminder that this is waiting for the next stable version.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.13
