### ISSUE TITLE
project watch errors

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#46]
Using emacs as my editor:
```
> nim project watch sample
Watching 'sample' [use Control-C to terminate]
(node:89528) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '.../scratch/sample/packages/default/.#hello.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using vi as my editor:
```
Deploying 'sample' due to change in 'sample/packages/default/hello.js'

Deployed actions ('nim action get <actionName> --url' for URL):
  - hello
Deployment complete.  Resuming watch.


Deploying 'sample' due to change in 'sample/packages/default/hello.js'

Deployed actions ('nim action get <actionName> --url' for URL):
  - hello
Failures:
 ›   Error: While deploying action .hello.js.swp: Action '.hello.js.swp' not 
 ›   deployed: runtime type could not be determined
```

**Comment by joshuaauerbachwatson** [comment]
At least two things are going on here. 

1.  The `.swp` suffix is not recognized as part of the current "editor temporaries" pattern used by project watch.  That may or may not be implicated in the second error (it's impossible to tell which change fired the watcher) but it might well be.
2. The exclusions for the watcher are not aligned with the exclusions of the deployer and the latter are missing some things in the former.    This accounts for the first error.   When emacs is saving, it first writes the new file (which fires the watcher) then erases the temporary.  But, depending on event interleaving, the temporary may still be there when the project reader is figuring out what is in the project.   In between when the project reader noticed the file and when it went to process it, it was erased by emacs.  But, the project reader should have ignored it anyway.

At the moment, file exclusions in the deployer focus on files that are "permanent but uninteresting", like `foo~` rather than files that are both temporary and uninteresting, like `.#foo`.

The whole area of files excluded from consideration by the deployer should be unified in one place and both the watcher and the deployer should use the same list.

**Comment by joshuaauerbachwatson** [comment]
@bhageena we discussed that you were open to more issues and I'd like to assign this one to you.   I wouldn't worry too much about the exact scenario that Rodric reported.  The basic idea is

1.  Find all the places in the deployer and the watcher where we are excluding files (like editor temporaries and backup files) that should be "uninteresting."
2. Make one function in the deployer but exported for use in the watcher that consolidates these exclusions and make sure this always what is used.
3. Add additional well-known editor temporaries to the list (e.g. `.swp`).
4. (Optional, don't go crazy with it) improve the logic to use more powerful pattern matching and be a bit more declarative so it's easier to add more.

**Comment by rabbah** [comment]
Is this OK to close now since 1.14 is out?
