### ISSUE TITLE
General project feedback

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#50]
Here are some half-baked ideas for project improvements based on my initial getting set up to fix the first issue. 

- Add basic build step in project CI/CD. Just run basic build steps in Github Actions on PRs and changes to allow PRs to validate whether any of the TS has broken and project builds correctly. 
- Automate deployment of the NPM module versions from tagged releases of the project. I used to do this on the official openwhisk NPM module before Apache complained at us.
- Move to webpack or another build tool to support handling all the TS building and minifying of the production version of the library rather than manually handling with custom NPM run scripts. 
- Add Depend-a-bot to ensure project dependencies stay up to date. 
- Start to adding unit tests with new features. This can be ran in the CI/CD for the project.

**Comment by joshuaauerbachwatson** [comment]
> * run basic build steps in Github Actions on PRs

Also lint, maybe?   Good idea.   Could you make a separate issue for this?  If you want to assign it to yourself go for it 🙂 .

> * Automate deployment of the NPM module versions

Perhaps.  The process by which Nimbella Corp currently releases versions is not sourced in this repo and does not typically involve `npm publish`.   But, we are moving toward using `npm publish` (we already do it for the storage providers and will eventually do it for all the npm packages in `nim`).  As we do, we should be driving it from this repo.   Whether or not we then automate it through tagging is choice that will come up then.  So, let's defer this until we have made the changeover.

> * Move to webpack or another build tool

I'm not specifically resistant to this idea but I'm curious first to find out what's wrong with what we are doing now since there are a lot of things we _could_ do.   If you want to pursue it further, let's discuss here for a while and make a separate issue if we want to act on it.

> * Add Depend-a-bot

I was under the impression we were already using Depend-a-bot.  At least it is sending me warnings 🙂 .

> * unit tests

This indicates a point in time in moving from closed source to open source.   Nimbella Corp. 
 does have many tests for features in this code.  They are not in this repo.   I agree that this repo deserves to have a good suite of tests and that those tests should be a large fraction of what we rely upon in production.    This will require some work within Nimbella to accomplish.

**Comment by jthomas** [comment]
> > * run basic build steps in Github Actions on PRs
> 
> Also lint, maybe? Good idea. Could you make a separate issue for this? If you want to assign it to yourself go for it 🙂 .

Will open an issue for this. 

> > * Automate deployment of the NPM module versions
> 
> Perhaps. The process by which Nimbella Corp currently releases versions is not sourced in this repo and does not typically involve `npm publish`. But, we are moving toward using `npm publish` (we already do it for the storage providers and will eventually do it for all the npm packages in `nim`). As we do, we should be driving it from this repo. Whether or not we then automate it through tagging is choice that will come up then. So, let's defer this until we have made the changeover.
> 
> > * Move to webpack or another build tool
> 
> I'm not specifically resistant to this idea but I'm curious first to find out what's wrong with what we are doing now since there are a lot of things we _could_ do. If you want to pursue it further, let's discuss here for a while and make a separate issue if we want to act on it.

There's definitely nothing wrong with the current approach - I was more thinking out loud about potential enhancements. I thought using webpack (or another standard build tool) would allow you to simplify the `package.json` scripts section from a series of manual commands to standardise on a single tool for running all the build stages (build TS, minify, tree shake modules...).

> > * Add Depend-a-bot
> 
> I was under the impression we were already using Depend-a-bot. At least it is sending me warnings 🙂 .

Looking at [this page](https://github.com/nimbella/nimbella-cli/network/updates) it doesn't seem to be enabled unless I'm missing something?

> > * unit tests
> 
> This indicates a point in time in moving from closed source to open source. Nimbella Corp.
> does have many tests for features in this code. They are not in this repo. I agree that this repo deserves to have a good suite of tests and that those tests should be a large fraction of what we rely upon in production. This will require some work within Nimbella to accomplish.

**Comment by rabbah** [comment]
> Looking at this page it doesn't seem to be enabled unless I'm missing something?

I think you're right - we get warnings but not auto PRs.

**Comment by rabbah** [comment]
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

**Comment by rabbah** [comment]
> Looking at this page it doesn't seem to be enabled unless I'm missing something?

I think you're right - we get warnings but not auto PRs.

Looks like we need a config file. Recommended interval?
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

**Comment by jthomas** [comment]
I'd vote for `weekly` to condense the number of PRs you get.

**Comment by joshuaauerbachwatson** [comment]
I have no experience with this.  I defer to you guys.

**Comment by rabbah** [comment]
Created config for the bot https://github.com/nimbella/nimbella-cli/blob/master/.github/dependabot.yml

**Comment by rabbah** [comment]
Of the initial set of suggestions, I think "unit tests with new features" is the outstanding item - with other points already covered by others issues or merged PRs. While moving the tests from the private repo to the public repo will take time, it does make sense to start "now" on new PRs against this repo... So I propose that we agree new PRs will require unit tests and if there is agreement to close this issue as resolved for now. In case of objections, let's discuss them.

In there is agreement, then the question is which testing framework to use - and I further propose we use `jest` with coverage, and to incrementally tighten the coverage requirement as we add new tests (or migrate existing tests) over time.

**Comment by joshuaauerbachwatson** [comment]
I agree that this issue should be closed since only the question of testing strategy remains and other points have been covered.   I'm hoping the following reservations don't require us to keep the issue open.   Just things to think about.

I accept that unit tests should be required for new PRs, and `jest` is ok with me.

I am skeptical about even talking about "coverage" at this point, when we have historically developed the code in this repo supported primarily by functional tests, with no unit testing requirement.

Better, IMO, is to add a modest functional verification test to this repo.
    - that could be covered by a new issue
    - it would be in addition to a simple requirement that new code be unit tested
    - I think it would help open source contributors more than some coverage metric because it could detect breakages when most code paths are currently not covered (not guaranteed that it _would_ detect such breakages, but we can at least address the most essential functions and those most likely to break)
    - it would be easier for us to do than any effort to greatly increase unit test coverage since we can base the new test on tests we currently run outside this repo

**Comment by jthomas** [comment]
Agree with all of the comments above. Would be good to have a simple functional test running automatically whilst the unit test coverage increases over time. 👍 on jest.

**Comment by rabbah** [comment]
Closing according to reached consensus. Whoever draws the short straw writes the first public/unit test 😅 🙏 🏃‍♂️
