### ISSUE TITLE
auth switch with namespace common to multiple hosts

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#52]
Say there are two namespaces, both with the same name `S`, but on two different hosts. If you `nim auth switch S` the CLI will instruct you to qualify the host because there are multiple matches.

I propose extending the disambiguation which exists for one host and multiple namespace matching a prefix (`nim auth switch prefix-`) to allow selection between hosts.

**Comment by bhageena** [comment]
Isn't it already in place, if I understand the desired behavior correctly? 
![Screenshot from 2021-03-02 02-51-27](https://user-images.githubusercontent.com/14236753/109560839-5a4bcc00-7b02-11eb-894c-4adc5ee7f443.png)

**Comment by rabbah** [comment]
Supper the namespace “example” exists two two hosts. The selection menu doesn’t include multiple hosts.

**Comment by bhageena** [comment]
Update: switching with a prefix is working as expected, yet to try with the exact name, the namespace renaming via the portal is not working currently.    
![Screenshot from 2021-03-02 03-32-54](https://user-images.githubusercontent.com/14236753/109565414-6fc3f480-7b08-11eb-836d-8312c11e1497.png)

**Comment by rabbah** [comment]
Interesting - If the namespace name is identical, you get the error:
```
 ›   Error: The namespace '...' exists on more than one API host.  An '--apihost' argument is required
```

**Comment by joshuaauerbachwatson** [comment]
The error is the expected behavior as of now.   But,  I thought the purpose of this issue was to replace that behavior and absorb the multiple API host case into the prompt feature.   Of course, Rodric, it's your issue ... so who am I to state its purpose?  But that was my understanding.

**Comment by rabbah** [comment]
> I  thought the purpose of this issue was to replace that behavior and absorb the multiple API host case into the prompt feature. 

Correct - a developer should be able to switch between namespaces on different API hosts without specifying `--apihost`. Chandan was pointing out that this is the behavior when the namespace names are unique across hosts, but (as a bug) `auth switch` reports an error when the value of the namespace is identical on multiple hosts.

**Comment by joshuaauerbachwatson** [comment]
A subtlety came up during the review of PR #80 concerning backward compatibility and the role of the trailing hyphen to indicate a request for namespace name completion.

We agree that a trailing hyphen should not suddenly be considered erroneous.   The existing PR accepts a trailing hyphen. 

I think we all agree that a trailing hyphen should not be required when the full namespace name has been typed and we are simply triggering the new feature, which is to prompt if that namespace exists on multiple API hosts.

@rabbah expressed the opinion that the trailing hyphen could always be optional and @bhageena tacitly agreed by implementing that.   I disagree.

Suppose I have two namespaces `bob` and `boosters`.  I type `nim ns clean boo --force` but I intended to clean `bob` rather than `boosters` and I just made a typo.   In the past, I would have been saved from cleaning the wrong namespace by the fact that it takes a positive indication (a trailing hyphen) to indicate that I am abbreviating the name.   Now it will go ahead and do it because there is no distinction between a complete name and an abbreviated name.

I know this is not a highly likely scenario and I would say that if it had always been that way I would certainly leave it.  But I think this makes the change not backward compatible because a protection that used to be there has been removed.

**Comment by rabbah** [comment]
I agree with you. I made the comment too casually (I hadn’t reviewed the code either) and the implied context (for me) was auth switch. Destructive operations should continue to offer protection and I intended no semantic change there. I retract my comment in the pr - the first change should be semantic preserving. Subsequent discussion can optionally ensue about where if any to relax the - requirement (and perhaps for consistency, not anywhere).

**Comment by bhageena** [comment]
I think it always has been this way. The guard was, explicitly requiring a `-` at the end, It would trigger a prompt or do the silent auto selection, depending number of matches found.

While a mandatory `-` does provide an extra cognitive load to be more careful, typos might happen nonetheless, `nim ns clean boo- --force` 

But I see no harm in expecting the user to express intent, explicit is better than implicit after all.

**Comment by rabbah** [comment]
This is part of 1.14. Close?

**Comment by joshuaauerbachwatson** [comment]
Yes.
