### ISSUE TITLE
add --yes to confirm nim auth logout (without a prompt)

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#54]
When asked to logout, there is a prompt which asks the user to confirm the logout. As a convenience, what about adding `--yes` to skip the confirmation?

**Comment by joshuaauerbachwatson** [comment]
Note that the prompt only occurs when you issue `nim logout` with no namespace argument, meaning you want to log out of the current namespace.   The motivation for the prompt is based on the idea that having no current namespace is a situation you might not want to be in.

My practice is always to switch to another namespace first and then `nim logout <ns>`.

I'm not opposed to a `--yes` (or `--force`, to be more consistent with prompt-suppression on other `nim` commands).   But, I think `--switch-to <ns>` would be preferable (automating my usual practice).  Note that all namespaces can be abbreviated.   I guess for users with only one namespace we'd still need a `--yes` or `--force` flag.

It might also be interesting to have a default namespace which you always return to when logging out of another one that is current.

A question for you.   What's the semantic difference between `question` and `discussion`?   To me they are identical ("things that are not yet actionable until we decide that they are").

**Comment by rabbah** [comment]
> My practice is always to switch to another namespace first and then nim logout <ns>.

I do the inverse. Logout then switch (because I don't have to then type out the name of the `ns` to logout). This is often (for me) better because of namespace conflicts on multiple hosts which means I also need to `--apihost` the logout command with a `ns`. (Related to #52)

> What's the semantic difference between question and discussion

Should have labeled it discussion (now fixed). This was not about asking for clarification/something that was poorly understood.

**Comment by joshuaauerbachwatson** [comment]
There are frequent requests for added convenience in `auth switch` and `auth logout` with which I sympathize but I find hard to motivate in terms of likely customer pain points (particularly where multiple API hosts are involved).   In this case, I think, we can exit discussion mode with the decision that since it's @rabbah requesting it and also the most likely consumer for a while,  we'll adopt his simple syntax and semantics for it.   But, it isn't going to be a priority for me.

Choices:

1.  Rodric assign yourself and just do it.
2. Label it a good first issue and see if anyone wants to pick it up (yes, it is a small issue and good for a warmup).
3. Let me do the usual, which is to self-assign but put it in the backlog for now.  I'll look to either get to it or find someone else eager for a small issue.

**Comment by rabbah** [comment]
Labeled accordingly.

**Comment by rabbah** [comment]
At the risk of broadening this, I'm finding that `yes | nim kv clean` sometimes works and sometimes doesn't. where works means the confirmation is recognized and other times not. I did not try to log what the cli is seeing but this is unfriendly to ci.

**Comment by joshuaauerbachwatson** [comment]
But, kv clean accept a --force (-f) flag, which suppresses the prompt.   So, broadening to include kv clean doesn't seem necessary.   I think the task is, rather, to find all the places where we require a prompt / response to take some action and make sure there is a --force (-f) flag on each such place.   Since @bhageena has taken this issue, it's kind of up to him how far to take this but I support the idea of being consistent.

**Comment by rabbah** [comment]
+1 for consistency. I forgot about -f on redis.

**Comment by bhageena** [comment]
Added #74 to address it.

**Comment by rabbah** [comment]
This is completed and released. Close?

**Comment by joshuaauerbachwatson** [comment]
Yes.
