### ISSUE TITLE
ESLint check misses files from source directory. 

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#59]
Whilst working on PR #58 I noticed `npm run lint` skip lots of the source files from being checked.

If you add the `--debug` flag to the end of the "lint" command value - you can see the following line in the debug output which lists the CLI arguments. The first glob expansion argument (`src/**/*.ts`) is automatically expanded to be individual source files and the glob pattern isn't being handled correctly. 

```
 eslint:cli CLI args: [ 'src/commands/doc.ts', 'src/commands/info.ts', 'src/deployer/index.ts', 'src/generator/project.ts', 'src/generator/samples.ts', 'src/hooks/prerun.ts', 'src/storage/clients.ts', 'src/storage/key-value.ts', 'src/storage/util.ts', 'deployer/src/**/*.ts', '--ignore-pattern', 'node_modules', '--debug' ]
```

This was very confusing! Digging around online I discovered the cause of this issue: https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

> But when you use this as a NPM script, NPM is using /bin/sh (so Bash 3.2 on OS X) that doesn’t recognize the ** expression and treats the glob as `src/*/*.js`. No top-level directory or subdirectories.

The fix is easy (`eslint 'src/**/*.ts' 'deployer/src/**/*.ts'`) but this now leads to a huge amount of ESLint errors. 

```
✖ 1263 problems (1161 errors, 102 warnings)
  1059 errors and 0 warnings potentially fixable with the `--fix` option.
```

@joshuaauerbachwatson What's your opinion on fixing huge amounts of lint errors like this? If we decide not to run the linter in the build process - this is not an issue.

**Comment by joshuaauerbachwatson** [comment]
I commented elsewhere that we ought to run the linter in the build process and I had already fixed the few that it had caught.

I continue to think that

- we ought to run the linter
- we ought to fix all those lint errors (just not right now).   We should schedule a time soonish to fix them all when we can have a temporary moratorium on conflicting PRs.  I have gone through this once before when I instituted lint in the first place.  It isn't great fun but we should be able to get through it
- since we aren't fixing them as our immediately highest priority, we might start out not running the linter at push time until we fix the errors

Does that sound ok or do you have some other thoughts about how to proceed?

**Comment by jthomas** [comment]
That sounds like a good approach. As you mentioned you're fixing the current caught lint errors in another change, the build process will soon pass with the current lint command. Once we're ready to embark on the lint-a-thon fix work - we just need to change over the lint command to escape the glob pattern and it'll start complaining about all the things we need to fix. We can park this issue until we're ready to start?

**Comment by joshuaauerbachwatson** [comment]
> We can park this issue until we're ready to start?

Sounds like a plan.

**Comment by joshuaauerbachwatson** [comment]
Taking the liberty of assigning both myself and @jthomas so we don't forget about it.   I notice that the bulk of the found errors were auto-fixable.   So, I propose that the next time there is a lull in PRs, I will just run the autofix, quick test, and commit.  That will leave a manageable number.

Then we can divide the work to fix the remainder, giving us two non-conflicting PRs.

I will look to find or create a lull in PRs soon.  The three outstanding PRs are all currently assigned to @bhageena.  None has serious obstacles to merging but two are labelled drafts and have small questions pending in the related issues.   The other needs a small addition as discussed in the issue.

**Comment by joshuaauerbachwatson** [comment]
We are now in the lull because Chandan graciously upped the priority of his PRs and I was able to merge them all.   I turned on the fix to the lint target as recommended by @jthomas and indeed there were many coverage omissions.   I let it autofix the new errors.   As I've found before using eslint with typescript, a few of the autofixes caused type errors (these are not deep ... when we fix everything properly we can address them by tweaking type declarations).   For now I just reversed those autofixes.  I will commit the resulting pervasive change once I confirm it is semantics-preserving by running some tests.   The commit will not include fixing the lint target itself since that will cause problems until the remaining lint errors are fixed.

**Comment by joshuaauerbachwatson** [comment]
We are now down to 165 errors when I use the fixed lint target (and none when I use the current broken one).    The remaining errors are spread across 72 files, which is a pretty low density.   It sounded so easy to say we will divide up the work to fix the remainder but I'm actually not sure that's best because the _kind_ of error is repeated a lot and, once you work out what you're going to do about an error of a given kind, it would be more efficient for one person to just do it across all the files.  Pausing progress on this hoping @jthomas has some suggestions on how to accomplish the remaining work.   There is no official moratorium on PRs so we might have to wait for another window of opportunity unless we want to just bite the bullet now.

**Comment by joshuaauerbachwatson** [comment]
I was between things and decided to give the remaining errors and warnings a go.  It looks like I'll just get through them in another hour or so, so, @jthomas, you are off the hook.

**Comment by jthomas** [comment]
@joshuaauerbachwatson Thanks for this - I've just started catching up on this ticket. Do you want to update the lint command in `package.json` now everything is fixed? Nice work on this!

**Comment by joshuaauerbachwatson** [comment]
> Do you want to update the lint command in `package.json` now everything is fixed? We should add the storage source dirs to the lint command as well? 

Yes, would you finish the final steps to enable the checking?   I forgot to commit that change.
